{{- if .Values.llmService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-knowledge-base.fullname" . }}-llm-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rag-knowledge-base.llmService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmService.service.type }}
  ports:
    - port: {{ .Values.llmService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rag-knowledge-base.llmService.selectorLabels" . | nindent 4 }}
{{- end }}
